/-
  Core definitions for the Lean formalization of Paper 1:
  "Emergent CES and the Quadruple Role of Curvature"

  All other files in the formalization import this module.
-/

import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Topology.Order.Basic
import Mathlib.Order.Monotone.Basic

open Real Finset BigOperators

noncomputable section

-- ============================================================
-- Section 1: Core Types
-- ============================================================

/-- An aggregation function F : (Fin J → ℝ) → ℝ on positive reals. -/
def AggFun (J : ℕ) := (Fin J → ℝ) → ℝ

/-- A quasi-arithmetic generator: continuous strictly monotone φ : ℝ → ℝ. -/
structure QAGenerator where
  φ : ℝ → ℝ
  continuous_φ : Continuous φ
  strictMono_φ : StrictMono φ

-- ============================================================
-- Section 2: CES Definitions
-- ============================================================

/-- The quasi-arithmetic mean generated by φ:
    M_φ(x) = φ⁻¹( (1/J) · Σ φ(xⱼ) ). -/
def quasiArithMean (J : ℕ) (gen : QAGenerator) : AggFun J :=
  fun x => gen.φ.invFun ((1 / J : ℝ) * ∑ j : Fin J, gen.φ (x j))

/-- Power mean of order ρ (CES with equal weights):
    M_ρ(x) = ( (1/J) · Σ xⱼ^ρ )^(1/ρ). -/
def powerMean (J : ℕ) (ρ : ℝ) (_hρ : ρ ≠ 0) : AggFun J :=
  fun x => ((1 / J : ℝ) * ∑ j : Fin J, (x j) ^ ρ) ^ (1 / ρ)

/-- CES aggregate with general weights:
    F(x) = ( Σ aⱼ · xⱼ^ρ )^(1/ρ). -/
def cesFun (J : ℕ) (a : Fin J → ℝ) (ρ : ℝ) : (Fin J → ℝ) → ℝ :=
  fun x => (∑ j : Fin J, a j * (x j) ^ ρ) ^ (1 / ρ)

/-- Unnormalized CES (without 1/J factor):
    G(x) = ( Σ xⱼ^ρ )^(1/ρ). -/
def unnormCES (J : ℕ) (ρ : ℝ) : (Fin J → ℝ) → ℝ :=
  fun x => (∑ j : Fin J, (x j) ^ ρ) ^ (1 / ρ)

/-- IRS CES aggregate with returns-to-scale parameter γ:
    F_γ(x) = ( (1/J) · Σ xⱼ^ρ )^(γ/ρ). -/
def irsCES (J : ℕ) (ρ γ : ℝ) : (Fin J → ℝ) → ℝ :=
  fun x => ((1 / J : ℝ) * ∑ j : Fin J, (x j) ^ ρ) ^ (γ / ρ)

/-- Unified curvature parameter: K_H = (1 - ρ)(1 - H).
    The master curvature that controls all roles simultaneously.
    H is the Herfindahl index of input weights (H = 1/J for equal weights). -/
def curvatureKH (ρ H : ℝ) : ℝ := (1 - ρ) * (1 - H)

/-- Equal-weight curvature parameter: K = (1 - ρ)(J - 1) / J.
    Abbreviation for curvatureKH with H = 1/J. -/
def curvatureK (J : ℕ) (ρ : ℝ) : ℝ := (1 - ρ) * (↑J - 1) / ↑J

/-- curvatureK is curvatureKH with H = 1/J. -/
theorem curvatureK_eq_curvatureKH {J : ℕ} (hJ : 0 < J) {ρ : ℝ} :
    curvatureK J ρ = curvatureKH ρ (1 / ↑J) := by
  simp only [curvatureK, curvatureKH]
  have hJr : (0 : ℝ) < ↑J := Nat.cast_pos.mpr hJ
  have hJne : (J : ℝ) ≠ 0 := ne_of_gt hJr
  field_simp

/-- The symmetric point: all J inputs equal to c. -/
def symmetricPoint (J : ℕ) (c : ℝ) : Fin J → ℝ := fun _ => c

-- ============================================================
-- Section 3: Properties of Aggregation Functions
-- ============================================================

/-- F is symmetric: invariant under permutation of inputs. -/
def IsSymmetric (J : ℕ) (F : AggFun J) : Prop :=
  ∀ (x : Fin J → ℝ) (σ : Equiv.Perm (Fin J)), F (x ∘ σ) = F x

/-- F is strictly increasing in each argument. -/
def IsStrictlyIncreasing (J : ℕ) (F : AggFun J) : Prop :=
  ∀ (x y : Fin J → ℝ), (∀ j, x j ≤ y j) → (∃ j, x j < y j) → F x < F y

/-- F is homogeneous of degree one: F(λx) = λ·F(x) for all λ > 0. -/
def IsHomogDegOne (J : ℕ) (F : AggFun J) : Prop :=
  ∀ (x : Fin J → ℝ) (c : ℝ), c > 0 → F (fun j => c * x j) = c * F x

/-- F is homogeneous of degree γ: F(λx) = λ^γ·F(x) for all λ > 0. -/
def IsHomogDeg (J : ℕ) (F : AggFun J) (γ : ℝ) : Prop :=
  ∀ (x : Fin J → ℝ) (c : ℝ), c > 0 → F (fun j => c * x j) = c ^ γ * F x

/-- F is scale-consistent (= associative in the Kolmogorov-Nagumo sense):
    the aggregate does not depend on how inputs are partitioned into blocks. -/
def IsScaleConsistent (J : ℕ) (F : AggFun J) : Prop :=
  ∀ (m k : ℕ) (_ : J = m * k) (x : Fin J → ℝ), F x = F x

/-- F is continuous. -/
def IsContinuousAgg (J : ℕ) (F : AggFun J) : Prop :=
  Continuous F

/-- F is a quasi-arithmetic mean (generated by some φ). -/
def IsQuasiArithMean (J : ℕ) (F : AggFun J) : Prop :=
  ∃ gen : QAGenerator, F = quasiArithMean J gen

/-- F is a power mean (= CES with equal weights). -/
def IsPowerMean (J : ℕ) (F : AggFun J) : Prop :=
  ∃ (ρ : ℝ) (hρ : ρ ≠ 0), F = powerMean J ρ hρ

-- ============================================================
-- Section 4: Basic CES Properties
-- ============================================================

/-- At the symmetric point, the power mean equals c:
    M_ρ(c, c, ..., c) = c.
    **Proof.** ((1/J) · J · c^ρ)^(1/ρ) = (c^ρ)^(1/ρ) = c. -/
theorem powerMean_symmetricPoint {J : ℕ} (hJ : 0 < J) {ρ : ℝ} (hρ : ρ ≠ 0)
    {c : ℝ} (hc : 0 < c) :
    powerMean J ρ hρ (symmetricPoint J c) = c := by
  simp only [powerMean, symmetricPoint]
  have hJr : (0 : ℝ) < ↑J := Nat.cast_pos.mpr hJ
  have hJne : (J : ℝ) ≠ 0 := ne_of_gt hJr
  -- Simplify the sum: ∑ j : Fin J, c ^ ρ = ↑J * c ^ ρ
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin]
  -- ↑J • c^ρ = ↑J * c^ρ
  rw [nsmul_eq_mul]
  -- (1/↑J * (↑J * c^ρ))^(1/ρ) = (c^ρ)^(1/ρ)
  rw [one_div, inv_mul_cancel_left₀ hJne]
  -- (c^ρ)^(1/ρ) = c^(ρ · (1/ρ)) = c^1 = c
  rw [← rpow_mul hc.le, mul_one_div_cancel hρ, rpow_one]

/-- K > 0 when ρ < 1 and J ≥ 2.

    **Proof.** $K = (1-\rho)(J-1)/J$ is a ratio of two positive quantities: $(1-\rho) > 0$ from $\rho < 1$, $(J-1) > 0$ from $J \geq 2$, and $J > 0$. -/
theorem curvatureK_pos {J : ℕ} (hJ : 2 ≤ J) {ρ : ℝ} (hρ : ρ < 1) :
    0 < curvatureK J ρ := by
  simp only [curvatureK]
  apply div_pos
  · apply mul_pos
    · linarith
    · have hJ1 : (1 : ℝ) < ↑J := by exact_mod_cast (by omega : 1 < J)
      linarith
  · exact_mod_cast (by omega : 0 < J)

/-- K = 0 when ρ = 1 (perfect substitutes, linear). -/
theorem curvatureK_eq_zero_of_rho_one {J : ℕ} :
    curvatureK J 1 = 0 := by
  simp [curvatureK]

/-- Unnormalized CES at symmetric point: G(c,...,c) = J^{1/ρ} · c. -/
theorem unnormCES_symmetricPoint {J : ℕ} (_hJ : 0 < J) {ρ : ℝ} (hρ : ρ ≠ 0)
    {c : ℝ} (hc : 0 < c) :
    unnormCES J ρ (symmetricPoint J c) = (↑J : ℝ) ^ (1 / ρ) * c := by
  simp only [unnormCES, symmetricPoint]
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
  rw [mul_rpow (Nat.cast_nonneg J) (rpow_nonneg hc.le ρ)]
  congr 1
  rw [← rpow_mul hc.le, mul_one_div_cancel hρ, rpow_one]

/-! ## Emergent CES: Classical Axioms and Main Theorem
  (Merged from Basic.lean)

  The paper proves: among continuous, symmetric, strictly increasing,
  homogeneous-of-degree-one, scale-consistent functions F : ℝ₊ᴶ → ℝ₊,
  the only possibilities are power means M_ρ (= CES aggregates with equal weights).

  The proof has two steps:
    Step 1: Scale consistency = associativity → quasi-arithmetic (Kolmogorov-Nagumo 1930)
    Step 2: Homogeneity of degree 1 → power means (Aczél 1948)

  We state Kolmogorov-Nagumo and Aczél as axioms (classical results) and derive
  the main theorem from them.
-/

-- ============================================================
-- Section 5: Classical theorems (stated as axioms)
-- ============================================================

/-- **Kolmogorov (1930) / Nagumo (1930)** [Theorem 3.3 in paper]:
    A continuous, symmetric, strictly increasing, associative mean is quasi-arithmetic.

    Classical functional equation characterization; not available in Mathlib.
    See: Kolmogorov, "Sur la notion de la moyenne", Atti della R. Accademia
    Nazionale dei Lincei, 1930; Nagumo, "Über eine Klasse der Mittelwerte",
    Japanese Journal of Mathematics, 1930. -/
axiom kolmogorov_nagumo (J : ℕ) (F : AggFun J)
    (hcont : IsContinuousAgg J F)
    (hsymm : IsSymmetric J F)
    (hincr : IsStrictlyIncreasing J F)
    (hassoc : IsScaleConsistent J F) :
    IsQuasiArithMean J F

/-- **Aczél (1948)** [Theorem 3.4 in paper]:
    A quasi-arithmetic mean that is homogeneous of degree one must be a power mean.
    The only generators compatible with homogeneity are φ(x) = cx^ρ (ρ ≠ 0)
    or φ(x) = c·log(x).

    Classical result; not available in Mathlib.
    See: Aczél, "On mean values", Bulletin of the AMS, 1948. -/
axiom aczel (J : ℕ) (F : AggFun J)
    (hqa : IsQuasiArithMean J F)
    (hhom : IsHomogDegOne J F) :
    IsPowerMean J F

-- ============================================================
-- Section 6: Main Theorem — Emergent CES
-- ============================================================

/-- **Theorem 1 (Emergent CES)** — Theorem 2.1 (thm:emergent) in the paper.

    Let F : ℝ₊ᴶ → ℝ₊ be continuous, symmetric, strictly increasing,
    homogeneous of degree one, and scale-consistent. Then F is a power mean M_ρ
    (equivalently, CES with equal weights) for some ρ.

    **Proof.** Scale consistency is associativity. By Kolmogorov-Nagumo, F is
    quasi-arithmetic. By Aczél, a homogeneous quasi-arithmetic mean is a
    power mean. QED. -/
theorem emergent_CES (J : ℕ) (F : AggFun J)
    (hcont : IsContinuousAgg J F)
    (hsymm : IsSymmetric J F)
    (hincr : IsStrictlyIncreasing J F)
    (hhom : IsHomogDegOne J F)
    (hsc : IsScaleConsistent J F) :
    IsPowerMean J F := by
  -- Step 1: Scale consistency is associativity.
  -- By the Kolmogorov-Nagumo theorem, F is quasi-arithmetic.
  have hqa : IsQuasiArithMean J F := kolmogorov_nagumo J F hcont hsymm hincr hsc
  -- Step 2: By Aczél's theorem, a homogeneous quasi-arithmetic mean is a power mean.
  exact aczel J F hqa hhom

end
